version: "3.9"

services:
  main-backend:
    image: ghcr.io/samithiwat/samithiwat-backend:latest
    container_name: samithiwat-app-backend
    restart: always

    env_file:
      - prod.env
    environment:
      DATABASE_HOST: db

    networks:
      - samithiwat-app

  db:
    image: postgres:14.1
    container_name: samithiwat-app-db
    restart: unless-stopped

    env_file:
      - prod.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./volumes/postgres:/volumes/postgresql/data
    networks:
      - samithiwat-app
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    command: -p ${DATABASE_PORT}

networks:
  samithiwat-app:
    name: samithiwat-app
