version: "3.9"

services:
  main-backend:
    image: ghcr.io/samithiwat/samithiwat-backend:latest
    container_name: main-backend-service
    restart: always

    env_file:
      - prod.env
    environment:
      DATABASE_HOST: "db"

  db:
    image: postgres:14.1
    container_name: samithiwat-db
    restart: unless-stopped

    env_file:
      - prod.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./volumes/postgres:/volumes/postgresql/data
    networks:
      - samithiwat
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    command: -p ${DATABASE_PORT}

networks:
  samithiwat:
    name: samithiwat
