version: "3.9"

services:
  main-backend:
    image: ghcr.io/samithiwat/samithiwat-backend:latest
    container_name: samithiwat-app-backend
    restart: always
    env_file:
      - prod.env
    environment:
      DATABASE_HOST: db
    networks:
      - samithiwat-app
      - traefik-net
    depends_on:
      - "db"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main-backend.rule=Host(`api.samithiwat.dev`)"
      - "traefik.http.routers.main-backend.entrypoints=web"
      - "traefik.docker.network=traefik-net"
  db:
    image: postgres:14.1
    container_name: samithiwat-app-db
    restart: unless-stopped

    env_file:
      - prod.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./volumes/postgres:/volumes/postgresql/data
    networks:
      - samithiwat-app
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    command: -p ${DATABASE_PORT}

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:2.6.1
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    networks:
      - traefik-net
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`api.samithiwat.dev`) && Path(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.docker.network=traefik-net"
    networks:
      - samithiwat-app
      - traefik-net

networks:
  samithiwat-app:
    name: samithiwat-app
  traefik-net:
    name: traefik-net
