version: "3.9"

services:
  local-db:
    image: postgres:14.1
    container_name: samithiwat-db
    restart: unless-stopped

    env_file:
      - dev.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./volumes/postgres:/volumes/postgresql/data
    networks:
      - samithiwat
    ports:
      - ${DATABASE_PORT}:5432

  local-cache:
    image: bitnami/redis:6.2.6
    container_name: samithiwat-cache
    restart: unless-stopped

    env_file:
      - dev.env
    networks:
      - samithiwat
    ports:
      - ${REDIS_PORT}:6379

networks:
  samithiwat:
    name: samithiwat
