app:
  port: ${PORT}
  debug: ${DEBUG}

database:
  port: ${DATABASE_PORT}
  host: ${DATABASE_HOST}
  name: ${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  ssl: ${POSTGRES_SSL_MODE}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

github:
  username: ${}