// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/samithiwat/samithiwat-backend/src/database"
	"github.com/samithiwat/samithiwat-backend/src/graph/resolver"
	"github.com/samithiwat/samithiwat-backend/src/repository/gorm"
	"github.com/samithiwat/samithiwat-backend/src/service"
)

// Injectors from wire.go:

func InitializeResolver(db database.Database) (*graph.Resolver, error) {
	gormRepository := repository.NewGormRepository(db)
	validatorService := service.NewValidatorService()
	imageService := service.NewImageService(gormRepository, validatorService)
	iconService := service.NewIconService(gormRepository, validatorService)
	badgeService := service.NewBadgeService(gormRepository, iconService, validatorService)
	aboutMeSettingService := service.NewAboutMeSettingService(gormRepository, validatorService)
	timelineSettingService := service.NewTimelineSettingService(gormRepository, iconService, imageService, validatorService)
	settingService := service.NewSettingService(gormRepository, aboutMeSettingService, timelineSettingService, validatorService)
	githubRepoService := service.NewGithubRepoService(gormRepository, badgeService, validatorService)
	resolver := graph.NewResolver(imageService, iconService, badgeService, aboutMeSettingService, timelineSettingService, settingService, githubRepoService)
	return resolver, nil
}
